# Generated by Django 4.0 on 2022-01-18 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='url',
            new_name='prj_url',
        ),
    ]
